#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-A-1 -d 10

bspc wm --reorder-monitors DisplayPort-1 HDMI-A-1

bspc config border_width         7
bspc config window_gap           15

bspc rule -a polybar window_gap=0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config focused_border_color "#ea999c"
bspc config normal_border_color "#f2d5cf"

bspc rule -a firefox border=off

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
